In [2]:
! pip install autogluon

Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.43.19-py3-none-any.whl.metadata (6.6 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 3.3 MB/s eta 0:00:00
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.13.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.4 MB/s eta 0:00:00
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.20.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.7)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.14)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.7-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (3.11.9)
Collecting chronos-forecasting<2.4,>=2.2.2 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading chronos_forecasting-2.2.2-py3-none-any.whl.metadata (23 kB)
Collecting peft<0.18,>=0.13.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (5.9.5)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (6.0.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (26.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (0.7.0)
Collecting botocore<1.44.0,>=1.43.19 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading botocore-1.43.19-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (1.17.0)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (4.0.0)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (3.7.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.70.16)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.7)
Requirement already satisfied: fastcore>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.13.2)
Requirement already satisfied: fasttransform>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (0.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (1.1.6)
Requirement already satisfied: plum-dispatch in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (2.9.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (3.1.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (3.13.5)
Collecting triad>=1.0.1 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading triad-1.0.2-py3-none-any.whl.metadata (6.6 kB)
Collecting adagio>=0.2.6 (from fugue>=0.9.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (3.29.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (1.5.0)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon) (0.10.9.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.5.0->autogluon) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.30.0)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting pytorch-lightning (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_lightning-2.6.5-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.9.0.post0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.60.0)
Collecting optuna (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting window-ops (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading window_ops-0.0.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.5.0->autogluon) (5.2.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (8.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<3.10,>=3.4.5->autogluon.multimodal==1.5.0->autogluon) (2025.11.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf<2.4.0,>=2.1.1->autogluon.multimodal==1.5.0->autogluon) (4.9.3)
Collecting colorama (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting model-index (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)
  Downloading model_index-0.1.11-py3-none-any.whl.metadata (3.9 kB)
Collecting opendatalab (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.5.0->autogluon)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
from google.colab import files

uploaded = files.upload()

Saving dataset.csv to dataset.csv

In [4]:
import pandas as pd

df = pd.read_csv('dataset.csv')

df.head()

,text,sentiment,text_length,clean_text
0,@looby_loo You are so full of good ideas Why ...,positive,69,you are so full of good ideas why didnt i thin...
1,"@marieez um ok, but i might not get there til ...",negative,91,um ok but i might not get there til like cos m...
2,is off to work for the day.,negative,28,is off to work for the day
3,@Dont_Panic42 ugh. You're so weird. Omg I ju...,negative,103,ugh youre so weird omg i just finished cleanin...
4,@fossiloflife tell him that he needs to fork o...,positive,84,tell him that he needs to fork out to the regu...

In [5]:
df.columns

Index(['text', 'sentiment', 'text_length', 'clean_text'], dtype='object')

In [6]:
from sklearn.model_selection import train_test_split

X = df['clean_text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 24000
Testing Samples: 6000

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=15000,
    ngram_range=(1,2),
    stop_words='english'
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print(X_train_tfidf.shape)

(24000, 15000)

In [8]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

lr_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=2000, random_state=42)

In [9]:
comment = ["This phone is amazing and works perfectly"]

comment_vector = tfidf.transform(comment)

prediction = lr_model.predict(comment_vector)

print(prediction)

['positive']

In [10]:
from autogluon.tabular import TabularPredictor
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df[['clean_text', 'sentiment']],
    test_size=0.2,
    random_state=42,
    stratify=df['sentiment']
)

print(train_df.shape)
print(test_df.shape)

(24000, 2)
(6000, 2)

In [11]:
predictor = TabularPredictor(
    label='sentiment',
    eval_metric='accuracy'
).fit(
    train_df,
    time_limit=1800  # 30 minutes
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260602_120616"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       10.61 GB / 12.67 GB (83.8%)
Disk Space Avail:   75.63 GB / 107.72 GB (70.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "/content/AutogluonModels/ag-20260602_120616"
Train Data Rows:    24000
Train Data Columns: 1
Label Column:       sentiment
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['positive', 'negative']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = positive, class 0 = negative
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (positive) vs negative (negative) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10868.33 MB
	Train Data (Original)  Memory Usage: 2.55 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['clean_text']
			CountVectorizer fit with vocabulary size = 1590
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('object', ['text']) : 1 | ['clean_text']
	Types of features in processed data (raw dtype, special dtypes):
		('category', ['text_as_category'])  :    1 | ['clean_text']
		('int', ['binned', 'text_special']) :    3 | ['clean_text.char_count', 'clean_text.word_count', 'clean_text.symbol_ratio. ']
		('int', ['text_ngram'])             : 1584 | ['__nlp__.able', '__nlp__.about', '__nlp__.about it', '__nlp__.about the', '__nlp__.about to', ...]
	13.3s = Fit runtime
	1 features in original data used to generate 1588 features in processed data.
	Train Data (Processed) Memory Usage: 72.60 MB (1.0% of available memory)
Data preprocessing and feature engineering runtime = 14.45s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 21600, Val Rows: 2400
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 1785.55s of the 1785.54s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.6/3.7 GB
	0.7704	 = Validation score   (accuracy)
	18.5s	 = Training   runtime
	0.44s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1766.42s of the 1766.41s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.6/10.3 GB
	0.7708	 = Validation score   (accuracy)
	10.9s	 = Training   runtime
	0.28s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 1755.14s of the 1755.13s of remaining time.
	Fitting with cpus=2, gpus=0, mem=0.1/10.4 GB
	0.7454	 = Validation score   (accuracy)
	165.46s	 = Training   runtime
	1.62s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 1580.36s of the 1580.34s of remaining time.
	Fitting with cpus=2, gpus=0, mem=0.1/10.5 GB
	0.7462	 = Validation score   (accuracy)
	169.79s	 = Training   runtime
	1.68s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 1402.47s of the 1402.46s of remaining time.
	Fitting with cpus=1, gpus=0, mem=2.1/10.4 GB
	0.7775	 = Validation score   (accuracy)
	262.47s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 1139.85s of the 1139.84s of remaining time.
	Fitting with cpus=2, gpus=0, mem=0.1/10.3 GB
	0.7579	 = Validation score   (accuracy)
	205.88s	 = Training   runtime
	1.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 926.72s of the 926.70s of remaining time.
	Fitting with cpus=2, gpus=0, mem=0.1/10.2 GB
	0.7629	 = Validation score   (accuracy)
	216.69s	 = Training   runtime
	1.17s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 701.36s of the 701.35s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.6/10.2 GB
	0.5625	 = Validation score   (accuracy)
	34.97s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 666.30s of the 666.28s of remaining time.
	Fitting with cpus=1, gpus=0, mem=1.1/10.2 GB
	0.7662	 = Validation score   (accuracy)
	143.55s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 522.59s of the 522.58s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.3/10.0 GB
	0.5617	 = Validation score   (accuracy)
	63.96s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 458.60s of the 458.58s of remaining time.
	Fitting with cpus=1, gpus=0, mem=1.6/10.0 GB
	0.7675	 = Validation score   (accuracy)
	15.17s	 = Training   runtime
	0.35s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 442.88s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/10.0 GB
	Ensemble Weights: {'CatBoost': 1.0}
	0.7775	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1358.71s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 21718.3 rows/s (2400 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2400 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260602_120616")

In [12]:
predictor.evaluate(test_df)

{'accuracy': 0.748,
 'balanced_accuracy': np.float64(0.7478826462496662),
 'mcc': np.float64(0.49609283794779796),
 'roc_auc': np.float64(0.8304648594447794),
 'f1': 0.7534246575342466,
 'precision': 0.742526518804243,
 'recall': 0.7646474677259185}

In [13]:
predictions = predictor.predict(test_df)

predictions.head()

6697     positive
28982    positive
21847    positive
18268    positive
18324    negative
Name: sentiment, dtype: object

In [14]:
sample = pd.DataFrame({
    'clean_text': [
        'this product is amazing',
        'worst experience ever',
        'i love this phone',
        'very disappointed'
    ],
    'text_length': [23, 21, 17, 17]
})

predictor.predict(sample)

0    positive
1    negative
2    positive
3    negative
Name: sentiment, dtype: object

In [15]:
from autogluon.tabular import TabularPredictor

predictor = TabularPredictor.load(
    "/content/AutogluonModels/ag-20260602_120616"
)

In [21]:
user_comment = input("Enter Instagram comment: ")

input_df = pd.DataFrame({
    'clean_text': [user_comment],
    'text_length': [len(user_comment)]
})

prediction = predictor.predict(input_df)

print("\nPredicted Sentiment:", prediction.iloc[0])

Enter Instagram comment: "This actor abuses so much , i hate him"

Predicted Sentiment: negative

In [22]:
import pandas as pd

user_comment = input("Enter Instagram comment: ")

input_df = pd.DataFrame({
    'clean_text': [user_comment],
    'text_length': [len(user_comment)]
})

prediction = predictor.predict(input_df)
probabilities = predictor.predict_proba(input_df)

print("\nComment:", user_comment)
print("Predicted Sentiment:", prediction.iloc[0])

print("\nConfidence Scores:")
print(probabilities)

Enter Instagram comment: "I don't like it as much it's tested better by lot's of people"

Comment: "I don't like it as much it's tested better by lot's of people"
Predicted Sentiment: positive

Confidence Scores:
   negative  positive
0  0.194765  0.805235

In [38]:
import pandas as pd

while True:
    user_comment = input("\nEnter comment (type 'exit' to quit): ")

    if user_comment.lower() == 'exit':
        break

    input_df = pd.DataFrame({
        'clean_text': [user_comment],
        'text_length': [len(user_comment)]
    })

    prediction = predictor.predict(input_df)
    probabilities = predictor.predict_proba(input_df)

    print("Predicted Sentiment:", prediction.iloc[0])
    print(probabilities)

Enter comment (type 'exit' to quit): The movie had great acting , but story was boring
Predicted Sentiment: negative
   negative  positive
0  0.670414  0.329586

Enter comment (type 'exit' to quit): exit

In [24]:
import shutil

shutil.make_archive(
    "autogluon_model",
    "zip",
    "/content/AutogluonModels/ag-20260602_120616"
)

'/content/autogluon_model.zip'

In [26]:
! pip install streamlit

Collecting streamlit
  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.47.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.29)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.21.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.15)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 32.6 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 32.1 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.2 streamlit-1.58.0

In [28]:
from google.colab import files

files.download("autogluon_model.zip")

In [27]:
import streamlit as st
import pandas as pd
from autogluon.tabular import TabularPredictor

# Load model
@st.cache_resource
def load_model():
    return TabularPredictor.load("predictor")

predictor = load_model()

st.title("📊 Instagram Sentiment Analyzer")

st.write("Analyze Instagram comments using AutoGluon AI")

comment = st.text_area(
    "Enter Instagram Comment",
    height=150
)

if st.button("Analyze Sentiment"):

    if comment.strip():

        input_df = pd.DataFrame({
            "clean_text": [comment],
            "text_length": [len(comment)]
        })

        prediction = predictor.predict(input_df)

        probabilities = predictor.predict_proba(input_df)

        st.success(
            f"Predicted Sentiment: {prediction.iloc[0]}"
        )

        st.subheader("Confidence Scores")

        st.dataframe(probabilities)

        st.bar_chart(probabilities.T)

    else:
        st.warning("Please enter a comment.")

2026-06-02 12:47:31.312 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
WARNING: Could not find version file at "/content/predictor/version.txt".
This means that the predictor was fit in an AutoGluon version `<=0.3.1`.

FileNotFoundError: [Errno 2] No such file or directory: '/content/predictor/predictor.pkl'